### PR TITLE
TCL 2020 and Carbon Flux

### PR DESCRIPTION
**Pull request by jterry64**
Upgrades to using new geotrellis jar, which includes both TCL 2020 and carbon flux columns.

### CODE REVIEW

**Comment by thomas-maschler** [comment]
Don't you need to set the executor memory etc?

**Comment by jterry64** [comment]
> Don't you need to set the executor memory etc?

When I was updating the configurations for geotrellis 3.5, the dev from azavea recommended to just try to use the maximizeResourceAllocation param instead of manually setting these. I haven't had any issues with using that, and successfully ran full annual update on in an hour yesterday with that configuration, so it seems fine. 

Do you think there will be an issues? I remember you said you occasionally got memory issues when running annualupdate, but it's been fine for me.

**Comment by thomas-maschler** [comment]
Ok, I initially ran it with `maximizeResourceAllocation` and ran into all sorts of memory issues. But this was along time ago. Let's try this and see if it works.

**Review by thomas-maschler — APPROVED** [review]

**Review by dagibbs22 — APPROVED** [review]
I don't think any of this directly affects the carbon flux analysis since the carbon flux analysis is now part of the Geotrellis package this uses.

**Pull request merged**
